flags: {}
extra-package-dbs: []
packages:
- adventofcode16
- adventofcode1601
- adventofcode1602
- adventofcode1603
- adventofcode1604
- adventofcode1605
- adventofcode1606
- adventofcode1607
- adventofcode1608
- adventofcode1609
- adventofcode1610
- adventofcode1611
- adventofcode1612
- adventofcode1613
- adventofcode1614
- adventofcode1615
- adventofcode1616
- adventofcode1617
- adventofcode1618
- adventofcode1619
- adventofcode1620
- adventofcode1621
- adventofcode1622
- adventofcode1623
- adventofcode1624
- adventofcode1625
system-ghc: true
extra-deps:
- astar-0.3.0.0
- parsec-numbers-0.1.0
- pqueue-1.3.2
resolver: lts-6.27
