flags: {}
extra-package-dbs: []
packages:
- adventofcode16
- adventofcode1601
- adventofcode1602
- adventofcode1624
system-ghc: true
extra-deps:
- astar-0.3.0.0
- parsec-numbers-0.1.0
- pqueue-1.3.2
resolver: lts-6.25
